import React from "react";

const Privacy = () => {
  return (
    <div className='bg-[#fff]'>
      <div className='lg:ps-[3rem] xs:ps-[1.8rem] px-[0.75rem] lg:w-[85%] pt-[5rem]'>
        <ol className='list-decimal'>
          <h1 className='text-[#111827] text-[30px] leading-[36px] font-[800] font-poppins lg:ms-[-3rem]'>Privacy Policy</h1>
          <li className='text-[17px] font-[700] items-justify mt-5'>Introduction</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>mailblink Inc. (“Company,” or “we,” “our,” or “us”) respects your privacy, and we are committed to protecting it through our compliance with this <br /> policy.</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>This Privacy Policy (our “Privacy Policy”) describes the types of information we may collect from you or that you may provide when you visit or <br /> use our website located at https://www.mailblink.com/ (our “Website”) and our practices for collecting, using, maintaining, protecting, and <br /> disclosing that information. For purposes of this Privacy Policy, our Website and all related services and functionality that we provide through <br /> them are referred to as our “Digital Services”. </p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>This policy applies to information we collect:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>on our Digital Services;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>in email, text, and other electronic messages between you and our Digital Services;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>when you interact with our advertising and applications on third party websites and services, if those applications or advertising include links to this policy.</li>
          </ul>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>It does not apply to information collected by:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>us offline or through any other means, including on any other website operated by Company or any third party;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>any third party, including through any application or content (including advertising) that may link to or be accessible from or on the Digital Services.</li>
          </ul>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>
            Please read this policy carefully to understand our policies and practices regarding your information and how we will treat it. If you do not agree with our policies and practices, your choice is not to use our Digital Services. By accessing or using our Digital Services, you agree to this Privacy Policy. This Privacy Policy may change from time to time (see, Changes to Our Privacy Policy). Your continued use of our Digital Services after we make changes is deemed to be acceptance of those changes, so please check this Privacy Policy periodically for updates.</p>
          <li className='text-[17px] font-[700] items-justify mt-5'>Children Under the Age of 16</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Our Digital Services are not intended for children under 16 years of age. No one under age 16 may provide any information to or through the Digital Services. We do not knowingly collect Personal Data from children under 16. If you are under 16, do not use or provide any information on or in our Digital Services or on or through any of their features, including your name, address, telephone number, email address, or any screen name or user name you may use. If we learn we have collected or received Personal Data from a child under 16 without verification of parental consent, we will delete that information. If you believe we might have any information from a child under 16, please contact us at privacy@mailblink.com.</p>
          <li className='text-[17px] font-[700] items-justify mt-5'>Information We Collect About You and How We Collect It</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Generally</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We collect several types of information from and about users of our Digital Services, specifically information:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>by which you may be personally identified, such as name, postal address, billing address, shipping address, e-mail address, credit or debit card number (for payment purposes only) (“Personal Data”); </li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>that is about you but individually does not identify you, such as traffic data, logs, referring/exit pages, date and time of your visit to or use of our Digital Services, error information, clickstream data, and other communication data and the resources that you access and use on or through our Digital Services; or</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>about your Internet connection, the equipment you use to access or use our Digital Services and usage details.</li>
          </ul>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We collect this information:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>directly from you when you provide it to us;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>automatically as you navigate through or use our Digital Services (which may include estimated or precise geo-location, usage details, IP addresses, and information collected through cookies and other tracking technologies); and</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>from third parties (e.g., our business partners).</li>
          </ul>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Information You Provide to Us</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The information we collect on or through our Digital Services is:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Personal Data such as the data identified above;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>information that you provide by filling in forms on our Digital Services (including information provided (i) at the time of registering to use our Digital Services, (ii) when using our services or other services available through the Digital Services, purchasing products, or requesting further services, or (iii) when you report a problem with our Digital Services);</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>information that you provide by filling in forms on our Digital Services (including information provided (i) at the time of registering to use our Digital Services, (ii) when using our services or other services available through the Digital Services, purchasing products, or requesting further services, or (iii) when you report a problem with our Digital Services);</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>details of transactions you carry out through our Digital Services and of the fulfillment of your orders (including financial information you are required to provide before placing an order through our Digital Services).</li>
          </ul>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>You also may provide information to be published or displayed (hereinafter, “posted”) on public areas of the Digital Services or transmitted to other users of the Digital Services or third parties (collectively, “User Contributions”). Your User Contributions are posted on and transmitted to others at your own risk. Although we limit access to certain pages, please be aware that no security measures are perfect or impenetrable. Additionally, we cannot control the actions of other users of the Digital Services with whom you may choose to share your User Contributions. Therefore, we cannot and do not guarantee that your User Contributions will not be viewed by unauthorized persons.</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Information We Collect Through Automatic Data Collection Technologies</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>As you navigate through and interact with our Digital Services, we may use automatic data collection technologies to collect certain information about your equipment, browsing actions, and patterns, specifically:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>details of your visits to our Digital Services, such as traffic data, location, logs, referring/exit pages, date and time of your visit to or use of our Digital Services, error information, clickstream data, and other communication data and the resources that you access and use on or in the Digital Services; and</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>information about your computer, mobile device, and Internet connection, specifically your IP address, operating system and browser type.</li>
          </ul>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The information we collect automatically may include Personal Data or we may maintain it or associate it with Personal Data we collect in other ways or receive from third parties. It helps us to improve our Digital Services and to deliver a better and more personalized service by enabling us to:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>estimate our audience size and usage patterns;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>store information about your preferences, allowing us to customize our Digital Services according to your individual interests; and</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>recognize you when you return to our Digital Services.</li>
          </ul>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The technologies we use for this automatic data collection may include:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Cookies. We and our service providers may use cookies, web beacons, and other technologies to receive and store certain types of information whenever you interact with our Digital Services through your computer or mobile device. A cookie is a small file or piece of data sent from a website and stored on the hard drive of your computer or mobile device. On your computer, you may refuse to accept browser cookies by activating the appropriate setting on your browser, and you may have similar capabilities on your mobile device in the preferences for your operating system or browser. However, if you select this setting you may be unable to access or use certain parts of our Digital Services. Unless you have adjusted your browser or operating system setting so that it will refuse cookies, our system will issue cookies when you direct your browser to our Website. </li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>{`Google Analytics. We use Google Analytics, a web analytics service provided by Google, Inc. (“Google”) to collect certain information relating to your use of our Website. Google Analytics uses “cookies”, which are text files placed on your computer, to help our Website analyze how users use the site. You can find out more about how Google uses data when you visit our Website by visiting “How Google uses data when you use our partners' sites or apps”, (located at www.google.com/policies/privacy/partners/). We may also use Google Analytics Advertising Features or other advertising networks to provide you with interest-based advertising based on your online activity. For more information regarding Google Analytics please visit Google's website, and pages that describe Google Analytics, such as www.google.com/analytics/learn/privacy.html. `}</li>
          </ul>
          <li className='text-[17px] font-[700] items-justify mt-5'>How We Use Your Information</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We use information that we collect about you or that you provide to us, including any Personal Data:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to provide our Website and its functionality, contents and services to;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to provide our products and services to you;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to provide you with information, products, or services that you request from us or that may be of interest to you;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to process, fulfill, support, and administer transactions and orders for products and services ordered by you;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to provide you with notices about your Company account;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to contact you in response to a request;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to fulfill any other purpose for which you provide it;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to carry out our obligations and enforce our rights arising from any contracts entered into between you and us, including for billing and collection;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to notify you about changes to our Digital Services or any products or services we offer or provide though them;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>in any other way we may describe when you provide the information; and</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>for any other purpose with your consent.</li>
          </ul>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We may also use your information to contact you about goods and services that may be of interest to you, including through newsletters. If you wish to opt-out of receiving such communications, you may do so at any time by clicking unsubscribe at the bottom of these communications or by visiting your Notification Settings page. For more information, see, Choices About How We Use and Disclose Your Information.</p>
          <li className='text-[17px] font-[700] items-justify mt-5'>Disclosure of Your Information</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We do not share, sell, or otherwise disclose your Personal Data for purposes other than those outlined in this Privacy Policy. However, we may disclose aggregated information about our users, and information that does not identify any individual, without restriction. </p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We may disclose Personal Data that we collect or you provide as described in this Privacy Policy:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to affiliates, contractors, service providers, and other third parties we use to support our business (e.g., third parties providing IT and infrastructure support services, and ordering, marketing, and payment processing services);</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to a buyer or other successor in the event of a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of our assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Company about our Digital Services users are among the assets transferred;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to fulfill the purpose for which you provide it;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>for any other purpose disclosed by us when you provide the information; and</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>with your consent.</li>
          </ul>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We may also disclose your Personal Data:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to comply with any court order, law, or legal process, including to respond to any government or regulatory request;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to affiliates and third parties to market their products or services to you if you have not opted out of these disclosures (see, Choices About How We Use and Disclose Your Information);</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>to enforce or apply our Terms of Use and other agreements, including for billing and collection purposes; and</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>if we believe disclosure is necessary or appropriate to protect the rights, property, or safety of Company, our customers, or others (including exchanging information with other companies and organizations for the purposes of fraud protection and credit risk reduction).</li>
          </ul>
          <li className='text-[17px] font-[700] items-justify mt-5'>Choices About How We Use and Disclose Your Information</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We do not control the collection and use of your information collected by third parties described above in Disclosure of Your Information. These third parties may aggregate the information they collect with information from their other customers for their own purposes.</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>In addition, we strive to provide you with choices regarding the Personal Data you provide to us. We have created mechanisms to provide you with control over your Personal Data:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Tracking Technologies and Advertising. You can set your browser or operating to refuse all or some cookies, or to alert you when cookies are being sent. If you disable or refuse cookies, please note that some parts of our Digital Services may then be inaccessible or not function properly</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Promotional Offers from Company. If you do not wish to have your email address used by Company to promote our own products and services, you can opt-out at any time by clicking the unsubscribe link at the bottom of any email or other marketing communications you receive from us or logging onto your Notification Settings page. This opt out does not apply to information provided to Company as a result of a product purchase, or your use of our services. You may have other options with respect to marketing and communication preferences through our Digital Services.</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Disclosure of Your Information to Affiliates and Third Parties. By using our Digital Services, you consent to our sharing of your Personal Data with our affiliates and third parties for their promotional purposes. If you wish to unsubscribe from such affiliate and third parties’ promotions, you can do so by clicking the unsubscribe link at the bottom of any email or other marketing communications you receive from them. If you wish to opt-out of such sharing, please change your preferences in your Notification Settings page or email us privacy@mailblink.com. </li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Targeted Advertising. To Learn more about interest-based advertisements and your opt-out rights and options, visit the Digital Advertising Alliance and the Network Advertising Initiative websites (www.aboutads.info and www.networkadvertising.org). Please note that if you choose to opt out, you will continue to see ads, but they will not be based on your online activity. We do not control third parties’ collection or use of your information to serve interest-based advertising. However, these third parties may provide you with ways to choose not to have your information collected or used in this way. You can also opt out of receiving targeted ads from members of the NAI on its website.</li>
          </ul>
          <li className='text-[17px] font-[700] items-justify mt-5'>Your Rights Regarding Your Information and Accessing and Correcting Your Information</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>You can Contact Us to access and/or find out what information we have about you, and to correct that information. You can also review and change your Personal Data by logging into our Digital Services and visiting the Notification Settings sections of our Digital Services. You may also notify us through the Contact Information below of any changes or errors in any Personal Data we have about you to ensure that it is complete, accurate, and as current as possible or to delete your account. We cannot delete your personal information except by also deleting your account with us. We may also not be able to accommodate your request if we believe it would violate any law or legal requirement or cause the information to be incorrect. </p>
          <li className='text-[17px] font-[700] items-justify mt-5'>Do Not Track Signals</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Some web browsers permit you to broadcast a signal to websites and online services indicating a preference that they “do not track” your online activities. At this time, we do not honor such signals, but we currently do not use automated data collection technologies to collect information about your online activities over time and across third party websites or other online services (behavioral advertising).</p>
          <li className='text-[17px] font-[700] items-justify mt-5'>Data Security</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We have implemented measures designed to secure your Personal Data from accidental loss and from unauthorized access, use, alteration, and disclosure. We use encryption technology for information sent and received by us.</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The safety and security of your information also depends on you. Where you have chosen a password for the use of our Digital Services, you are responsible for keeping this password confidential. We ask you not to share your password with anyone.</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Unfortunately, the transmission of information via the Internet is not completely secure. Although we do our best to protect your Personal Data, we cannot guarantee the security of your Personal Data transmitted to, on or through our Digital Services. Any transmission of Personal Data is at your own risk. We are not responsible for circumvention of any privacy settings or security measures contained on the Website or in your operating system.</p>
          <li className='text-[17px] font-[700] items-justify mt-5'>California Privacy Rights for California Residents</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>These California Privacy Rights supplement the other information contained in our Privacy Policy and applies solely to all visitors, users, and others who reside in the State of California (“consumers” or “you”). This notice is to comply with the California Consumer Privacy Act of 2018 (“CCPA”) and any terms defined in the CCPA have the same meaning when used in this notice. We may update these California Privacy Rights as necessary and in the event of changes in the CCPA. These terms apply only to California residents.</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Categories of Personal Information Company Collects – California Residents</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>As described in more detail in other areas of our Privacy Policy, we collect and/or disclose Personal Information about you when you visit use our Digital Services, including information about you that you provide to us, and information that we automatically collect from you or your computer or device as you use our Digital Services. Please see, Information We Collect About You and How We Collect It for additional information and details.</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Personal information does not include information that is: (a) publicly available information from government records; (b) de-identified or aggregated consumer information; or (c) certain information excluded from the scope of CCPA (e.g., PHI covered under HIPAA and medical information covered under the California Medical Information Act).</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Categories of Sources from which Company has collected Personal Information</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We collect Personal Information directly from you, for example when you provide it to us, when you contact us through our Digital Services, when you create a Company account; and indirectly from you automatically through your computer or device as you use our Digital Services. We may also collect Personal Information about you from our advertising partners and service providers. </p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Use of Personal Information Collected from California Residents</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We do not sell your Personal Information and have not done so in the prior 12 months from the effective date of this Policy. We may use or disclose the personal information we collect for our business purposes described elsewhere in this Privacy Policy (e.g., see, How We Use Your Information and Disclosure of Your Information). </p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Sharing Personal Information - California Residents</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Company may disclose your Personal Information to a third party for one or more business purposes. When we disclose Personal Information for a business purpose, such as to service providers, we enter a contract that describes the purpose and requires the recipient to both keep that Personal Information confidential and not use it for any purpose except performing the contract. </p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Disclosures of Personal Information for Business Purposes</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We may disclose your Personal Information for our business purposes, such as your contact information, other information you have provided to us and unique identifiers that identify you to us or to our service providers, such as companies that assist us with marketing and advertising. Please see, Information We Collect About You and How We Collect It for additional information and details.</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Access Request Rights</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>California residence have the right to request that Company disclose certain information to you about our collection and use of your Personal Information over the past 12 months for the above business and commercial purposes (see, Exercising Access and Deletion Rights). Once we receive and confirm your verifiable consumer request, we will disclose to you:</p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>the categories of Personal Information we collected about you;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>the categories of sources for the Personal Information we collected about you;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>our business or commercial purpose for collecting that Personal Information;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>the categories of third parties with whom we share that Personal Information;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>the specific pieces of Personal Information we collected about you; and</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>if we sold or disclosed your Personal Information for a business purpose, two separate lists disclosing:</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>sales, identifying the Personal Information categories that each category of recipient purchased; and</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>disclosures for a business purpose, identifying the Personal Information categories that each category of recipient obtained. </li>
          </ul>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Deletion Request Rights</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>California residents have the right to request that Company delete your Personal Information that we collected from you and retained, subject to certain exceptions. Once we receive and confirm your verifiable consumer request, we will delete (and direct our service providers to delete) your Personal Information from our records, unless certain exceptions apply.</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Exercising Access and Deletion Rights</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>To exercise the access and deletion rights described above, please submit a verifiable consumer request to us by: </p>
          <ul className="list-disc">
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Emailing us at privacy@mailblink.com </li>
            <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Only you, or a person registered with the California Secretary of State that you authorize to act on your behalf, may make a verifiable consumer request related to your Personal Information. You may also make a verifiable consumer request on behalf of your minor child. You may only make a verifiable consumer request for access twice within a 12-month period. The verifiable consumer request must:</p>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Provide sufficient information that allows us to reasonably verify you are the person about whom we collected Personal Information or an authorized representative.</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Describe your request with sufficient detail that allows us to properly understand, evaluate, and respond to it.</li>
            <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Non-Discrimination</p>
            <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We will not discriminate against you for exercising any of your CCPA rights. Unless permitted by the CCPA, we will not:</p>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>deny you goods or services;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>charge you different prices or rates for goods or services, including through granting discounts or other benefits, or imposing penalties;</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>provide you a different level or quality of goods or services; or</li>
            <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>suggest that you may receive a different price or rate for goods or services or a different level or quality of goods or services.</li>
            <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Other California Privacy Rights</p>
            <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>California Civil Code Section 1798.83 (California’s “Shine the Light” law) permits users of our Digital Services that are California residents and who provide Personal Information in obtaining products and services for personal, family, or household use to request certain information regarding our disclosure of Personal Information to third parties for their own direct marketing purposes. If applicable, this information would include the categories of Personal Information and the names and addresses of those businesses with which we shared your Personal Information with for the immediately prior calendar year (e.g., requests made in 2021 will receive information regarding such activities in 2020). You may request this information once per calendar year. To make such a request, please contact us by email at privacy@mailblink.com.</p>
            <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>California Civil Code Section 1798.83 (California’s “Shine the Light” law) permits users of our Digital Services that are California residents and who provide Personal Data in obtaining products and services for personal, family, or household use to request certain information regarding our disclosure of Personal Data to third parties for their own direct marketing purposes. If applicable, this information would include the categories of Personal Data and the names and addresses of those businesses with which we shared your Personal Data with for the immediately prior calendar year (e.g., requests made in 2021 will receive information regarding such activities in 2020). You may request this information once per calendar year. To make such a request, see Contact Information below.</p>
          </ul>
          <li className='text-[17px] font-[700] items-justify mt-5'>Changes to Our Privacy Policy</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We may change this Privacy Policy at any time. It is our policy to post any changes we make to our Privacy Policy on this page with a notice that the Privacy Policy has been updated on the Website’s home page. If we make material changes to how we treat our users’ Personal Data, we will notify you by email to the email address specified in your account and/or through a notice on the Website’s home page. The date this Privacy Policy was last revised is identified at the top of the page. You are responsible for ensuring we have an up-to-date active and deliverable email address for you, and for periodically visiting our Website and reviewing this Privacy Policy to check for any changes.</p>
          <li className='text-[17px] font-[700] items-justify mt-5'>Contact Information</li>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>If you have any questions, concerns, complaints or suggestions regarding our Privacy Policy or otherwise need to contact us, you may contact us at the contact information below or through the Support page on or in our Digital Services.</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>How to Contact Us:</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Email:</p>
          <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>privacy@mailblink.com</p>
        </ol>
      </div>
    </div>
  )
};

export default Privacy
