import React from "react";

const Terms = () => {
  return (
    <div className='bg-[#fff]'>
      <div className='lg:ps-[3rem] xs:ps-[1.8rem] px-[0.75rem] md:px-[1rem] lg:w-[85%] pt-[5rem]'>
        <h1 className='text-[#111827] text-[30px] leading-[36px] font-[800] font-poppins lg:ms-[-3rem]'>Terms of Use</h1>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Acceptance of the Terms of Use</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>These terms of use are entered into by and between you (“you“ or “your”) and mailblink Inc. ( “we,” “us” or “our”). The following terms and conditions, together with any documents they expressly incorporate by reference (collectively, “Terms of Use”), govern your access to and use of our products, functionality and services, including without limitation, those provided through https://www.mailblink.com/ (collectively, “mailblink”), whether as a guest or a registered user.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Please read the Terms of Use carefully before you start to use mailblink. By using mailblink, you accept and agree to be bound and abide by these Terms of Use, our Publisher Agreement (if applicable) and our Privacy Policy, found at mailblink.com/privacy incorporated herein by reference. If you do not want to agree to the foregoing, you must not access or use mailblink</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>mailblink is offered and available to users who are 16 years of age or older. By using mailblink, you represent and warrant that you are of legal age to form a binding contract with us and meet all of the foregoing eligibility requirements. If you do not meet all of these requirements, you must not access or use mailblink.</p>

        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Changes to the Terms of Use</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We may revise and update these Terms of Use from time to time in our sole discretion. All changes are effective immediately when we post them, and apply to all access to and use of mailblink thereafter.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Your continued use of mailblink following the posting of revised Terms of Use means that you accept and agree to the changes. You are expected to check this page from time to time so you are aware of any changes, as they are binding on you. </p>

        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Accessing mailblink and Account Security</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We reserve the right to change any service or functionality we provide on mailblink, in our sole discretion without notice. We will not be liable if for any reason all or any part of mailblink is unavailable at any time or for any period. From time to time, we may restrict access to some parts of mailblink to users, including registered users.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>You are responsible for both:</p>
        <ul className="list-disc">
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Making all arrangements necessary for you to have access to mailblink.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Ensuring that all persons who access mailblink through your internet connection are aware of these Terms of Use and comply with them.</li>
        </ul>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>To access mailblink or some of the resources it offers, you may be asked to provide certain registration details or other information. It is a condition of your use of mailblink that all the information you provide on mailblink is correct, current, and complete. You agree that all information you provide to register with mailblink or otherwise, including, but not limited to, through the use of any interactive features on mailblink, is governed by our Privacy Policy, and you consent to all actions we take with respect to your information consistent with our Privacy Policy.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>If you choose, or are provided with, a user name, password, or any other piece of information as part of our security procedures, you must treat such information as confidential, and you must not disclose it to any other person or entity. You also acknowledge that your account is personal to you and agree not to provide any other person with access to mailblink or portions of it using your user name, password, or other security information. You agree to notify us immediately of any unauthorized access to or use of your user name or password or any other breach of security. You also agree to ensure that you exit from your account at the end of each session. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We have the right to disable any user name, password, or other identifier, whether chosen by you or provided by us, at any time in our sole discretion for any or no reason, including if, in our opinion, you have violated any provision of these Terms of Use.</p>

        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Intellectual Property Rights</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>{`mailblink's trademarks, logos, intellectual property, content, features, and functionality (including but not limited to all information, software, text, displays, images, video, and audio, and the design, selection, and arrangement thereof) are owned by mailblink, its licensors, or other providers of such content and are protected by United States and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws.`}</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Boosts Feature</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>{`Boosts is a feature available only to users on our scale plan that allows them to deposit funds for sponsored placements of their newsletters in other users' profiles. By using the Boosts feature, you agree to adhere to the following provisions:`}</p>
        <ol className='list-disc list-alphabet'>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>All deposits made for Boosts are non-refundable.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>mailblink takes a 15% cut of revenue from the seller side of the market, with an additional 5% reserved for fees.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Funds in your mailblink wallet may only be withdrawn if your account balance exceeds a $50 threshold. To initiate a withdrawal, click on “Withdraw Funds” in your mailblink Wallet, and a payout will be processed via Stripe to the Stripe account you created when registering for Boosts.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Only users who are legally able to access a Stripe account and are of the age legally allowed to accept payments may utilize the Boosts feature.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>There is no guarantee of performance for Boosts campaigns.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>To remain active in the Boosts marketplace, you must be actively sending newsletters on mailblink.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>If you attempt to circumvent the system and export subscribers from Boosts, you are liable to pay for those subscribers.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>If you attempt to circumvent the system in any way, we reserve the right to remove you from using the platform as a whole, moving forward. In this circumstance, you are not owed any sort of refund for either Boosts or the platform itself.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The content of Boosts campaigns must adhere to the Content Standards outlined in the Terms of Use.</li>
        </ol>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Prohibited Uses</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>You may use mailblink only for lawful purposes and in accordance with these Terms of Use. You agree not to use mailblink:</p>
        <ul className="list-disc">
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>In any way that violates any applicable federal, state, local, or international law or regulation (including, without limitation, any laws regarding the export of data or software to and from the US or other countries).</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>For the purpose of exploiting, harming, or attempting to exploit or harm minors in any way by exposing them to inappropriate content, asking for personally identifiable information, or otherwise.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>To send, knowingly receive, upload, download, use, or re-use any content that does not comply with these Terms of Use.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>To transmit, or procure the sending of, any advertising or promotional content, including any “junk mail,” “chain letter,” “spam,” or any other similar solicitation.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>To impersonate or attempt to impersonate us or a mailblink employee, another user, or any other person or entity (including, without limitation, by using email addresses associated with any of the foregoing).</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>To engage in any other conduct that restricts or inhibits anyone’s use or enjoyment of mailblink, or which, as determined by us, may harm mailblink or users of mailblink, or expose them to liability.</li>
        </ul>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Additionally, you agree not to:</p>
        <ul className="list-disc">
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Use mailblink in any manner that could disable, overburden, damage, or impair mailblink or interfere with any other party’s use of mailblink, including their ability to engage in real time activities through mailblink.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Use any robot, spider, or other automatic device, process, or means to access mailblink for any purpose, including monitoring or copying content on mailblink.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Use any manual process to monitor or copy content on mailblink, or for any other purpose not expressly authorized in these Terms of Use, without our prior written consent.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Use any device, software, or routine that interferes with the proper working of mailblink.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Introduce any viruses, Trojan horses, worms, logic bombs, or other material that is malicious or technologically harmful.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Attempt to gain unauthorized access to, interfere with, damage, or disrupt any parts of mailblink, the server on which mailblink is stored, or any server, computer, or database connected to mailblink. </li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Attack mailblink via a denial-of-service attack or a distributed denial-of-service attack.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Otherwise attempt to interfere with the proper working of mailblink.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Use the Boosts feature in any manner that violates the provisions outlined in the “Boosts Feature” section.</li>
        </ul>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Monitoring and Enforcement; Termination</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We have the right to:</p>
        <ul className="list-disc">
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Remove or refuse to publish any content for any or no reason in our sole discretion.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Take any action with respect to any content that we deem necessary or appropriate in our sole discretion, including if we believe that such content violates the Terms of Use, including the Content Standards, infringes any intellectual property right or other right of any person or entity, threatens the personal safety of users of mailblink or the public, or could create liability for mailblink.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Disclose your identity or other information about you to any third party who claims that content published by you violates their rights, including their intellectual property rights or their right to privacy.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Take appropriate legal action, including without limitation, referral to law enforcement, for any illegal or unauthorized use of mailblink. </li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Terminate or suspend your access to all or part of mailblink for any or no reason, including without limitation, any violation of these Terms of Use.</li>
        </ul>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Without limiting the foregoing, we have the right to cooperate fully with any law enforcement authorities or court order requesting or directing us to disclose the identity or other information of anyone publishing content on or through mailblink. YOU WAIVE AND HOLD HARMLESS mailblink AND ITS AFFILIATES, LICENSEES, AND SERVICE PROVIDERS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY ANY OF THE FOREGOING PARTIES DURING, OR TAKEN AS A CONSEQUENCE OF, INVESTIGATIONS BY EITHER SUCH PARTIES OR LAW ENFORCEMENT AUTHORITIES.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>However, we do not undertake to review content before it is published on mailblink, and cannot ensure prompt removal of objectionable content after it has been published. Accordingly, we assume no liability for any action or inaction regarding transmissions, communications, or content provided by any user or third party. We have no liability or responsibility to anyone for performance or nonperformance of the activities described in this section. </p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Content Standards</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>These content standards apply to any and all content published to mailblink. Content must in their entirety comply with all applicable federal, state, local, and international laws and regulations. Without limiting the foregoing, content must not:</p>
        <ul className="list-disc">
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Contain any material that is defamatory, obscene, indecent, abusive, offensive, harassing, violent, hateful, inflammatory, or otherwise objectionable.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Promote sexually explicit or pornographic material, violence, or discrimination based on race, sex, religion, nationality, disability, sexual orientation, or age.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Infringe any patent, trademark, trade secret, copyright, or other intellectual property or other rights of any other person.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Violate the legal rights (including the rights of publicity and privacy) of others or contain any material that could give rise to any civil or criminal liability under applicable laws or regulations or that otherwise may be in conflict with these Terms of Use, any applicable Publisher Agreement and/or our Privacy Policy.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Be likely to deceive any person.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Promote any illegal activity, or advocate, promote, or assist any unlawful act.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Cause annoyance, inconvenience, or needless anxiety or be likely to upset, embarrass, alarm, or annoy any other person.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Impersonate any person, or misrepresent your identity or affiliation with any person or organization. </li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Involve commercial activities or sales, such as contests, sweepstakes, and other sales promotions, barter, or advertising.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Give the impression that they emanate from or are endorsed by us or any other person or entity, if this is not the case.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>These content standards also apply to the content of Boosts campaigns.</li>
        </ul>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Copyright Infringement</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We take claims of copyright infringement seriously. We will respond to notices of alleged copyright infringement that comply with applicable law. If you believe any content accessible on or from mailblink infringe your copyright, you may request removal of such content (or access to them) from mailblink by submitting written notification to our copyright agent designated below. In accordance with the Online Copyright Infringement Liability Limitation Act of the Digital Millennium Copyright Act (17 U.S.C. § 512) (“DMCA”), the written notice (the “DMCA Notice”) must include substantially the following:</p>
        <ul className="list-disc">
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Your physical or electronic signature.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Identification of the copyrighted work you believe to have been infringed or, if the claim involves multiple works on mailblink, a representative list of such works.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Identification of the content you believe to be infringing in a sufficiently precise manner to allow us to locate that content.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Adequate information by which we can contact you (including your name, postal address, telephone number, and, if available, email address). </li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>A statement that the information in the written notice is accurate.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>A statement, under penalty of perjury, that you are authorized to act on behalf of the copyright owner.</li>
        </ul>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>You may submit a DMCA Notice by emailing DMCA@mailblink.com.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>If you fail to comply with all of the requirements of Section 512(c)(3) of the DMCA, your DMCA Notice may not be effective.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Please be aware that if you knowingly materially misrepresent that content or activity on mailblink is infringing your copyright, you may be held liable for damages (including costs and attorneys’ fees) under Section 512(f) of the DMCA.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>If you believe that content you published on mailblink was removed or access to it was disabled by mistake or misidentification, you may file a counter notification with us (a “Counter Notice”) by submitting written notification to our copyright agent designated above. Pursuant to the DMCA, the Counter Notice must include substantially the following:</p>
        <ul className="list-disc">
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Your physical or electronic signature.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>An identification of the content that has been removed or to which access has been disabled and the location at which the content appeared before it was removed or access disabled.</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Adequate information by which we can contact you (including your name, postal address, telephone number, and, if available, email address).</li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>A statement under penalty of perjury by you that you have a good faith belief that the content identified above was removed or disabled as a result of a mistake or misidentification of the content to be removed or disabled. </li>
          <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>A statement that you will consent to the jurisdiction of the Federal District Court for the judicial district in which your address is located (or if you reside outside the United States for any judicial district in which mailblink may be found) and that you will accept service from the person (or an agent of that person) who provided mailblink with the complaint at issue.</li>
        </ul>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The DMCA allows us to restore the removed content if the party filing the original DMCA Notice does not file a court action against you within ten business days of receiving the copy of your Counter Notice.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Please be aware that if you knowingly materially misrepresent that content or activity on mailblink was removed or disabled by mistake or misidentification, you may be held liable for damages (including costs and attorneys’ fees) under Section 512(f) of the DMCA.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>It is our policy in appropriate circumstances to disable and/or terminate the accounts of users who are repeat infringers.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Reliance on Information Published</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The information published on or through mailblink is made available solely for general information purposes. We do not warrant the accuracy, completeness, or usefulness of this information. Any reliance you place on such information is strictly at your own risk. We disclaim all liability and responsibility arising from any reliance placed on such content by you or any other visitor to mailblink, or by anyone who may be informed of any of its contents.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>mailblink includes content provided by third parties, including content provided by other users, publishers, and third-party licensors. All statements and/or opinions expressed in such content, and all articles and responses to questions and other content, other than the content provided by mailblink, are solely the opinions and the responsibility of the person or entity providing such content. Such third party content does not necessarily reflect the opinion of mailblink. We are not responsible, or liable to you or any third party, for the content or accuracy of any content provided by any third parties.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Information About You and Your Visits to mailblink</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>All information we collect on mailblink is subject to our Privacy Policy. By using mailblink, you consent to all actions taken by us with respect to your information in compliance with the Privacy Policy.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Linking to mailblink and Social Media Features</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>You may link to our homepage, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval, or endorsement on our part. </p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>mailblink may provide certain social media features that enable you to:</p>
        <ul className="list-disc">
         <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Link from your own or certain third-party websites to certain content on mailblink.</li>
         <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Send emails or other communications with certain content, or links to certain content, on mailblink.</li>
         <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Cause limited portions of content on mailblink to be displayed or appear to be displayed on your own or certain third-party websites.</li>
         <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>You may use these features solely as they are provided by us, solely with respect to the content they are displayed with, and otherwise in accordance with any additional terms and conditions we provide with respect to such features. Subject to the foregoing, you must not:</p>
         <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Establish a link from any website that is not owned by you.</li>
         <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Cause mailblink or portions of it to be displayed on, or appear to be displayed by, any other site, for example, framing, deep linking, or in-line linking.</li>
         <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Link to any part of mailblink other than the homepage.</li>
         <li className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Otherwise take any action with respect to content on mailblink that is inconsistent with any other provision of these Terms of Use.</li>
        </ul>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The website from which you are linking, or on which you make certain content accessible, must comply in all respects with the Content Standards set out in these Terms of Use.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>You agree to cooperate with us in causing any unauthorized framing or linking immediately to stop. We reserve the right to withdraw linking permission without notice.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>We may disable all or any social media features and any links at any time without notice in our discretion.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Links from mailblink</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>If mailblink contains links to other sites and resources provided by third parties, these links are provided for your convenience only. This includes links contained in advertisements, including banner advertisements and sponsored links. We have no control over the contents of those sites or resources, and accept no responsibility for them or for any loss or damage that may arise from your use of them. If you decide to access any of the third-party websites linked to mailblink, you do so entirely at your own risk and subject to the terms and conditions of use for such websites.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Reporting Abuse</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>To report spam originating from mailblink.com please forward the message to abuse@mailblink.com.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>If you suspect any attempts to circumvent the system or abuse related to Boosts, please report it to us for investigation. We will conduct an internal review and make a determination based on the gathered facts.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Geographic Restrictions</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The owner of mailblink is based in the State of New York in the United States. We make no claims that mailblink or any of its content is accessible or appropriate outside of the United States. Access to mailblink may not be legal by certain persons or in certain countries. If you access mailblink from outside the United States, you do so on your own initiative and are responsible for compliance with local laws.</p>
     
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>No Refunds</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>All sales are final and fully earned upon receipt. By using mailblink, you acknowledge and agree that you will not be entitled to a refund for any purchase under any circumstance.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Disclaimer of Warranties</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>You understand that we cannot and do not guarantee or warrant that files available for downloading from the internet or mailblink will be free of viruses or other destructive code. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for anti-virus protection and accuracy of data input and output, and for maintaining a means external to mailblink for any reconstruction of any lost data. TO THE FULLEST EXTENT PROVIDED BY LAW, WE WILL NOT BE LIABLE FOR ANY LOSS OR DAMAGE CAUSED BY A DISTRIBUTED DENIAL-OF-SERVICE ATTACK, VIRUSES, OR OTHER TECHNOLOGICALLY HARMFUL MATERIAL THAT MAY INFECT YOUR COMPUTER EQUIPMENT, COMPUTER PROGRAMS, DATA, OR OTHER PROPRIETARY MATERIAL DUE TO YOUR USE OF mailblink OR ANY SERVICES OR ITEMS OBTAINED THROUGH mailblink OR TO YOUR DOWNLOADING OF ANY CONTENT PUBLISHED ON IT, OR ON ANY WEBSITE LINKED TO IT.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>YOUR USE OF mailblink, ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH mailblink IS AT YOUR OWN RISK. mailblink, ITS CONTENT, AND ANY SERVICES OR ITEMS OBTAINED THROUGH mailblink ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS, WITHOUT ANY WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. NEITHER WE NOR ANY PERSON ASSOCIATED WITH US MAKES ANY WARRANTY OR REPRESENTATION WITH RESPECT TO THE COMPLETENESS, SECURITY, RELIABILITY, QUALITY, ACCURACY, OR AVAILABILITY OF mailblink. WITHOUT LIMITING THE FOREGOING, NEITHER WE NOR ANYONE ASSOCIATED WITH US REPRESENTS OR WARRANTS THAT mailblink, ITS CONTENT, OR ANY SERVICES OR ITEMS OBTAINED THROUGH mailblink WILL BE ACCURATE, RELIABLE, ERROR-FREE, OR UNINTERRUPTED, THAT DEFECTS WILL BE CORRECTED, THAT mailblink OR THE SERVER THAT MAKES IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR THAT mailblink OR ANY SERVICES OR ITEMS OBTAINED THROUGH mailblink WILL OTHERWISE MEET YOUR NEEDS OR EXPECTATIONS.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>TO THE FULLEST EXTENT PROVIDED BY LAW, WE HEREBY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO ANY WARRANTIES OF MERCHANTABILITY, NON-INFRINGEMENT, AND FITNESS FOR PARTICULAR PURPOSE.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>THE FOREGOING DOES NOT AFFECT ANY WARRANTIES THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Limitation on Liability</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>TO THE FULLEST EXTENT PROVIDED BY LAW, IN NO EVENT WILL WE, OUR AFFILIATES, OR OUR OR THEIR LICENSORS, SERVICE PROVIDERS, EMPLOYEES, AGENTS, OFFICERS, OR DIRECTORS BE LIABLE FOR DAMAGES OF ANY KIND, UNDER ANY LEGAL THEORY, ARISING OUT OF OR IN CONNECTION WITH YOUR USE, OR INABILITY TO USE, mailblink, ANY WEBSITES LINKED TO IT, OR ANY CONTENT ON mailblink, INCLUDING ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO, PERSONAL INJURY, PAIN AND SUFFERING, EMOTIONAL DISTRESS, LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The limitation of liability set out above does not apply to liability resulting from our gross negligence or willful misconduct.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>THE FOREGOING DOES NOT AFFECT ANY LIABILITY THAT CANNOT BE EXCLUDED OR LIMITED UNDER APPLICABLE LAW.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Indemnification</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>You agree to defend and indemnify us and our affiliates, licensors, and service providers, and our and their respective officers, directors, employees, contractors, agents, licensors, suppliers, successors, and assigns from and against any claims, liabilities, damages, judgments, awards, losses, costs, expenses, or fees (including reasonable attorneys’ fees) arising out of or relating to your violation of these Terms of Use or your use of mailblink, including, but not limited to, your published content, any use of mailblink’s content, services, and products other than as expressly authorized in these Terms of Use, or your use of any information obtained from mailblink.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Governing Law and Jurisdiction</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>All matters relating to mailblink and these Terms of Use, and any dispute or claim arising therefrom or related thereto (in each case, including non-contractual disputes or claims), will be governed by and construed in accordance with the internal laws of the State of New York without giving effect to any choice or conflict of law provision or rule (whether of the State of New York or any other jurisdiction).</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>Any legal suit, action, or proceeding arising out of, or related to, these Terms of Use or mailblink will be instituted exclusively in the federal courts of the United States or the courts of the State of New York, in each case located in the City of New York and County of New York. You waive any and all objections to the exercise of jurisdiction over you by such courts and to venue in such courts.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Arbitration</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>At our sole discretion, it may require You to submit any disputes arising from these Terms of Use or use of mailblink, including disputes arising from or concerning their interpretation, violation, invalidity, non-performance, or termination, to final and binding arbitration under the Rules of Arbitration of the American Arbitration Association applying New York law.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Limitation on Time to File Claims</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>ANY CAUSE OF ACTION OR CLAIM YOU MAY HAVE ARISING OUT OF OR RELATING TO THESE TERMS OF USE OR mailblink MUST BE COMMENCED WITHIN ONE YEAR AFTER THE CAUSE OF ACTION ACCRUES; OTHERWISE, SUCH CAUSE OF ACTION OR CLAIM IS PERMANENTLY BARRED.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Waiver and Severability</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>No waiver by us of any term or condition set out in these Terms of Use will be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of us to assert a right or provision under these Terms of Use will not constitute a waiver of such right or provision.</p>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>If any provision of these Terms of Use is held by a court or other tribunal of competent jurisdiction to be invalid, illegal, or unenforceable for any reason, such provision will be eliminated or limited to the minimum extent such that the remaining provisions of the Terms of Use will continue in full force and effect.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Entire Agreement</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>The Terms of Use, any applicable Publisher Agreement and our Privacy Policy constitute the sole and entire agreement between you and mailblink Inc. regarding mailblink and supersede all prior and contemporaneous understandings, agreements, representations, and warranties, both written and oral, regarding mailblink.</p>
        <h1 className='text-[17px] font-[700] items-justify mt-5 underline'>Your Comments and Concerns</h1>
        <p className='text-[1rem] font-[400] mt-5 font-poppins items-justify'>All other feedback, comments, requests for technical support, and other communications relating to mailblink should be directed to: privacy@mailblink.com.</p>

      </div>
    </div>
  )
};

export default Terms;
